### ISSUE TITLE
Support running outside of docker

### ISSUE THREAD

**Issue by eduardvercaemer** [blainehansen/migrator#1]
Firstly, this is amazingly useful. ❤️ 🦀 

What would you think of supporting running the program outside of docker ?

Maybe provide an optional connection string to use as the temporary db ? For simple cases even using the same connection but on a different db might even work.

**Comment by blainehansen** [comment]
I'd be happy to support use outside docker! It shouldn't be terribly difficult, I just have to register the crate as a binary on crates.io so it can be installed.
Stay tuned! I'll hopefully have time to do this on Sunday.

**Comment by blainehansen** [comment]
Now published as a Rust package :)
https://github.com/blainehansen/postgres_migrator#as-a-rust-binary
https://crates.io/crates/postgres_migrator

I also added some more docs explaining how to run it in the context of docker compose. Tell me if everything works as expected!
