### ISSUE TITLE
Create composite index concurrently?

### ISSUE THREAD

**Issue by MattDelac** [blainehansen/migrator#4]
First of all, congrats ! I love the idea of having clean schemas and then generate migrations from the diff of the current state. This is so clean !!!

Is there a way to create a composite index? And even better to have some controls like `CREATE INDEX CONCURRENTLY`?
Or should I just create a manual migration myself?

Cheers

**Comment by blainehansen** [comment]
Anything you can do in postgres you can do using this tool :) Just add the `create index concurrently` statement wherever you want in the `schema` files, and just modify it in the `migration` files if something such as the `concurrently` statement is left off.

Ultimately all the diff tool cares about is that the sql in the `schema` and `migration` files ends up with the same objects in the information tables, so however you achieve that is up to you!

**Comment by MattDelac** [comment]
> Anything you can do in postgres you can do using this tool :) Just add the `create index concurrently` statement wherever you want in the `schema` files, and just modify it in the `migration` files if something such as the `concurrently` statement is left off.
> 
> Ultimately all the diff tool cares about is that the sql in the `schema` and `migration` files ends up with the same objects in the information tables, so however you achieve that is up to you!

Amazing ! will try that later today.
I would advise to maybe showing one of those examples in the README for everyone who might have a similar question 🙂
