### ISSUE TITLE
Automatically determine ordering?

### ISSUE THREAD

**Issue by ZakSingh** [blainehansen/migrator#7]
I love this tool. Thank you for creating it!

An interesting feature would be to create a topological ordering from the schema files (or better, the statements within) so that there's no need to name schema files based on their dependencies, e.g. 1_xx, 2_xx, 3_xx...

Does such a feature align with the goals of the project?

**Comment by blainehansen** [comment]
Honestly yes it would! At least from the perspective of my *values*. But doing so would be sufficiently complicated I don't really think I have the time/priority for it :cry:

Frankly I'm getting more curious about projects like [edgedb](https://www.edgedb.com/showcase/migrations) that are just trying to holistically solve the problems with sql, including declarative migration patterns.

But if you think you come up with a reasonable way to design/implement this idea that doesn't break anything ha, I'd be open to it!
